# Generated by Django 4.2.20 on 2025-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=16, verbose_name="账号")),
                ("password", models.CharField(max_length=16)),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(1, "教师"), (2, "学生"), (3, "管理员")],
                        verbose_name="身份",
                    ),
                ),
            ],
        ),
    ]
