# Generated by Django 4.2.20 on 2025-05-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="role",
            field=models.SmallIntegerField(
                choices=[(1, "教师"), (2, "学生")], verbose_name="身份"
            ),
        ),
    ]
