# Generated by Django 4.2.20 on 2025-05-15 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_chapter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("filepath", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, null=True)),
                ("assign_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField()),
                ("type", models.SmallIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filepath", models.CharField(max_length=1024)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("grade", models.IntegerField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
    ]
