# Generated by Django 4.2.20 on 2025-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_assignment_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="type",
            field=models.SmallIntegerField(choices=[(1, "教师"), (2, "学生")]),
        ),
    ]
