# Generated by Django 4.2.20 on 2025-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_alter_assignment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="type",
            field=models.SmallIntegerField(choices=[(1, "个人作业"), (2, "小组作业")]),
        ),
    ]
