# Generated by Django 4.2.20 on 2025-05-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0009_alter_assignment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="course",
        ),
        migrations.AddField(
            model_name="submission",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
